version: 2

sphinx:
  configuration: doc/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements.txt
    - requirements: doc/requirements.txt
